# Generated by Django 4.2.1 on 2025-01-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedcomment',
            name='profile_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
