# Generated by Django 4.2.1 on 2024-11-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='deletedcomment',
            name='post',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='deletedcomment',
            name='user',
            field=models.CharField(max_length=400),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='User_profile',
        ),
    ]
