# Generated by Django 4.2.1 on 2024-11-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_remove_user_profile_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedcomment',
            name='channel_id',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
