# Generated by Django 4.2.1 on 2024-11-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0003_deletedcomment_channel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedcomment',
            name='channel_id',
            field=models.BigIntegerField(),
        ),
    ]
