# Generated by Django 4.2.1 on 2024-11-27 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0006_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedcomment',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_comments', to='moderation.owner'),
        ),
    ]
