# Generated by Django 4.2.1 on 2024-12-11 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0008_blockeduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockeduser',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moderation.deletedcomment'),
        ),
    ]
