# Generated by Django 4.2.1 on 2024-12-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0009_blockeduser_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockeduser',
            name='is_permanent',
            field=models.BooleanField(default=False),
        ),
    ]
