# Generated by Django 4.2.1 on 2024-12-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0010_blockeduser_is_permanent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockeduser',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
