# Generated by Django 4.2.1 on 2024-12-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0011_alter_blockeduser_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedcomment',
            name='detected_by',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
